name: cbs_notes_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  equatable: ^2.0.5
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
